base_url = "dentrassi.de"
title = "ctron's blog"
description = "Life, the Universe and Everything"

default_language = "en"

output_dir = "public"
template = "dentrassi"

compile_sass = true
minify_html = true
generate_feed = true

build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "OneHalfDark"

render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

smart_punctuation = true

[slugify]
paths = "on"

[search]
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
