base_url = "https://dentrassi.de"
title = "ctron's blog"
description = "Life, the Universe and Everything"

default_language = "en"

output_dir = "public"
theme = "dentrassi"

compile_sass = true
minify_html = false
generate_feed = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

smart_punctuation = true

[slugify]
paths = "on"
paths_keep_dates = false

[search]
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
