on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1

      - name: Install NPM dependencies
        working-directory: themes/dentrassi/build
        run: |
          npm ci

      - name: Build template
        working-directory: themes/dentrassi/build
        run: |
          npm run build

      - run: |
          zola build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
